// Banco IA — preguntas adicionales tipo UNAM Área 2 generadas siguiendo temario oficial.
// ~25 por materia. Cada una incluye `explanation`.
// NOTA: no son reactivos oficiales UNAM. Son preguntas modeladas a partir del estilo
// y temas del Examen Muestra 2025. Úsalas para práctica adicional.

const AI_QUESTIONS = {

  fisica: [
    { text: "Un automóvil viaja a velocidad constante de 72 km/h durante media hora. ¿Qué distancia recorre?",
      options: ["18 km", "36 km", "72 km", "144 km"],
      correct: 1,
      explanation: "72 km/h × 0.5 h = 36 km. Velocidad constante: d = v·t." },
    { text: "Un objeto en caída libre desde el reposo tarda 3 s en llegar al suelo. ¿Desde qué altura cayó? (g = 10 m/s²)",
      options: ["15 m", "30 m", "45 m", "90 m"],
      correct: 2,
      explanation: "h = ½gt² = ½(10)(9) = 45 m." },
    { text: "Dos vectores perpendiculares de 6 N y 8 N actúan sobre un punto. ¿Cuál es la magnitud del vector resultante?",
      options: ["2 N", "10 N", "14 N", "48 N"],
      correct: 1,
      explanation: "Por Pitágoras: R = √(6² + 8²) = √(36+64) = √100 = 10 N." },
    { text: "Una fuerza neta de 20 N actúa sobre un objeto de 4 kg. ¿Cuál es la aceleración del objeto?",
      options: ["0.2 m/s²", "5 m/s²", "16 m/s²", "80 m/s²"],
      correct: 1,
      explanation: "Por la 2ª ley de Newton: a = F/m = 20/4 = 5 m/s²." },
    { text: "¿Cuál es el peso de un cuerpo de 50 kg en la superficie terrestre? (g = 9.8 m/s²)",
      options: ["5.1 N", "50 N", "490 N", "980 N"],
      correct: 2,
      explanation: "P = m·g = 50 × 9.8 = 490 N. El peso es una fuerza, no una masa." },
    { text: "Un trabajador levanta una caja de 20 kg hasta una altura de 1.5 m. ¿Qué trabajo realiza? (g = 10 m/s²)",
      options: ["30 J", "150 J", "300 J", "3000 J"],
      correct: 2,
      explanation: "W = F·d = (m·g)·h = (20)(10)(1.5) = 300 J." },
    { text: "Si la energía cinética de un objeto se cuadruplica, su rapidez se multiplica por",
      options: ["1", "2", "4", "16"],
      correct: 1,
      explanation: "$E_c = \\frac{1}{2}mv^2$, depende del cuadrado de v. Para que $E_c$ se cuadruplique, v debe duplicarse." },
    { text: "¿Cuál es la unidad de potencia en el Sistema Internacional?",
      options: ["Newton", "Joule", "Watt", "Pascal"],
      correct: 2,
      explanation: "El Watt (W = J/s) mide energía por unidad de tiempo." },
    { text: "Una palanca de primer género tiene el punto de apoyo",
      options: ["en uno de los extremos.", "entre la fuerza aplicada y la resistencia.", "entre el centro de gravedad y la fuerza.", "fuera del brazo de carga."],
      correct: 1,
      explanation: "En palanca de primer género (ej. balanza), el pivote está entre la fuerza motriz y la resistencia." },
    { text: "Un cuerpo flota cuando su densidad",
      options: ["es mayor que la del fluido.", "es igual a la del fluido.", "es menor que la del fluido.", "es independiente del fluido."],
      correct: 2,
      explanation: "Principio de Arquímedes: si la densidad del objeto < densidad del fluido, flota." },
    { text: "¿Qué propiedad de un gas se mantiene constante en un proceso isotérmico?",
      options: ["Presión", "Volumen", "Temperatura", "Densidad"],
      correct: 2,
      explanation: "Isotérmico viene de iso (igual) + termo (temperatura)." },
    { text: "Las ondas sonoras son de tipo",
      options: ["transversales", "longitudinales", "electromagnéticas", "estacionarias únicamente"],
      correct: 1,
      explanation: "El sonido se propaga por compresiones y rarefacciones del medio, paralelas a la dirección de propagación → onda longitudinal." },
    { text: "Si la frecuencia de una onda es 50 Hz y su longitud de onda es 2 m, su velocidad de propagación es",
      options: ["25 m/s", "52 m/s", "100 m/s", "200 m/s"],
      correct: 2,
      explanation: "v = f·λ = 50 × 2 = 100 m/s." },
    { text: "¿Qué tipo de espejo siempre produce imágenes virtuales, derechas y de menor tamaño?",
      options: ["Plano", "Cóncavo", "Convexo", "Parabólico"],
      correct: 2,
      explanation: "El espejo convexo siempre produce imágenes virtuales, derechas y reducidas (por eso se usa en retrovisores)." },
    { text: "El fenómeno por el cual una onda cambia de dirección al pasar de un medio a otro se llama",
      options: ["reflexión", "refracción", "difracción", "interferencia"],
      correct: 1,
      explanation: "La refracción ocurre por cambio de velocidad del frente de onda al cambiar de medio." },
    { text: "Una resistencia de 10 Ω por la que circula una corriente de 2 A disipa una potencia de",
      options: ["5 W", "20 W", "40 W", "200 W"],
      correct: 2,
      explanation: "P = I²·R = (2)²·(10) = 40 W. También: P = V·I = (20)(2) = 40 W." },
    { text: "En un circuito con dos resistencias iguales en paralelo, la resistencia equivalente es",
      options: ["el doble de una de ellas", "la mitad de una de ellas", "igual a una de ellas", "cuatro veces una de ellas"],
      correct: 1,
      explanation: "Para resistencias iguales en paralelo: Req = R/n. Con n=2, Req = R/2." },
    { text: "La fuerza entre dos cargas eléctricas puntuales según la Ley de Coulomb es proporcional a",
      options: ["la distancia al cuadrado", "la distancia inversa", "el inverso de la distancia al cuadrado", "el cubo de la distancia"],
      correct: 2,
      explanation: "F = k·q₁·q₂/r². Inversamente proporcional al cuadrado de la distancia." },
    { text: "Una espira de alambre por la que circula corriente eléctrica genera un campo",
      options: ["gravitatorio", "magnético", "eléctrico estático", "nuclear"],
      correct: 1,
      explanation: "Una corriente eléctrica produce un campo magnético a su alrededor (descubrimiento de Oersted)." },
    { text: "La luz visible tiene longitudes de onda aproximadamente entre",
      options: ["1-10 nm", "400-700 nm", "1-10 μm", "1-10 mm"],
      correct: 1,
      explanation: "El espectro visible va de ~400 nm (violeta) a ~700 nm (rojo)." },
    { text: "Albert Einstein recibió el Nobel de Física por su trabajo en",
      options: ["la teoría de la relatividad especial.", "la teoría de la relatividad general.", "el efecto fotoeléctrico.", "la equivalencia masa-energía."],
      correct: 2,
      explanation: "Einstein recibió el Nobel en 1921 por su explicación del efecto fotoeléctrico, no por la relatividad." },
    { text: "La energía mínima requerida para extraer un electrón de un material por efecto fotoeléctrico se llama",
      options: ["energía cinética", "función de trabajo", "energía potencial", "constante de Planck"],
      correct: 1,
      explanation: "La función de trabajo (φ) es la energía umbral característica de cada material." },
    { text: "El principio de incertidumbre de Heisenberg establece que es imposible conocer simultáneamente, con precisión absoluta,",
      options: ["la masa y la energía de una partícula.", "la posición y el momento de una partícula.", "la carga y el spin de un electrón.", "la temperatura y la presión de un gas."],
      correct: 1,
      explanation: "Δx·Δp ≥ ℏ/2: hay un límite cuántico a la precisión combinada de posición y momento." },
    { text: "El núcleo atómico está compuesto por",
      options: ["protones y electrones", "neutrones y electrones", "protones y neutrones", "sólo protones"],
      correct: 2,
      explanation: "Los nucleones (protones y neutrones) forman el núcleo. Los electrones orbitan alrededor." },
    { text: "Si la masa de un objeto aumenta y su velocidad permanece constante, su momento lineal",
      options: ["disminuye proporcionalmente.", "se mantiene constante.", "aumenta proporcionalmente.", "se vuelve cero."],
      correct: 2,
      explanation: "p = m·v. Si v es constante y m aumenta, p aumenta proporcionalmente." },
  ],

  quimica: [
    { text: "El número atómico de un elemento corresponde al número de",
      options: ["neutrones en el núcleo", "protones en el núcleo", "electrones de valencia", "protones más neutrones"],
      correct: 1,
      explanation: "El número atómico (Z) es el número de protones, característico de cada elemento." },
    { text: "Un isótopo se diferencia del átomo neutro de un mismo elemento en el número de",
      options: ["protones", "electrones", "neutrones", "iones"],
      correct: 2,
      explanation: "Los isótopos tienen mismo Z (protones) pero diferente A (masa) por distinto número de neutrones." },
    { text: "La configuración electrónica del átomo de oxígeno (Z=8) es",
      options: ["1s² 2s² 2p²", "1s² 2s² 2p⁴", "1s² 2s² 2p⁶", "1s² 2s¹ 2p⁵"],
      correct: 1,
      explanation: "8 electrones: 2 en 1s, 2 en 2s, 4 en 2p → 1s² 2s² 2p⁴." },
    { text: "Los elementos del grupo I A son llamados",
      options: ["gases nobles", "halógenos", "metales alcalinos", "metales de transición"],
      correct: 2,
      explanation: "Grupo I A: H, Li, Na, K, Rb, Cs, Fr — los metales alcalinos (excepto H)." },
    { text: "El enlace covalente se forma cuando los átomos",
      options: ["transfieren electrones de uno a otro.", "comparten pares de electrones.", "ionizan completamente.", "intercambian protones."],
      correct: 1,
      explanation: "En el enlace covalente los átomos comparten electrones; en el iónico se transfieren." },
    { text: "¿Cuántos átomos hay en una molécula de glucosa (C₆H₁₂O₆)?",
      options: ["12", "18", "24", "30"],
      correct: 2,
      explanation: "6 + 12 + 6 = 24 átomos." },
    { text: "El pH de una disolución neutra a 25 °C es",
      options: ["0", "1", "7", "14"],
      correct: 2,
      explanation: "Por equilibrio del agua: pH 7 es neutro. Menor: ácido. Mayor: básico." },
    { text: "Según Arrhenius, un ácido es una sustancia que en disolución acuosa libera iones",
      options: ["OH⁻", "H⁺", "Na⁺", "Cl⁻"],
      correct: 1,
      explanation: "Ácido de Arrhenius: produce H⁺ (o H₃O⁺). Base: produce OH⁻." },
    { text: "El número de Avogadro es aproximadamente",
      options: ["6.022 × 10²³", "9.81", "1.602 × 10⁻¹⁹", "3.14159"],
      correct: 0,
      explanation: "6.022 × 10²³ partículas por mol — base de la estequiometría." },
    { text: "¿Cuál es la masa molar del agua (H₂O)? (H = 1 g/mol, O = 16 g/mol)",
      options: ["17 g/mol", "18 g/mol", "20 g/mol", "32 g/mol"],
      correct: 1,
      explanation: "2(1) + 16 = 18 g/mol." },
    { text: "Una disolución 1 M de NaCl contiene",
      options: ["1 g de NaCl por litro", "1 mol de NaCl por litro", "1 mol de NaCl por gramo", "1 g de NaCl por mol"],
      correct: 1,
      explanation: "Molaridad (M) = moles de soluto por litro de disolución." },
    { text: "En la reacción 2H₂ + O₂ → 2H₂O, ¿cuántos moles de agua se producen al reaccionar 4 moles de H₂?",
      options: ["2", "3", "4", "8"],
      correct: 2,
      explanation: "Relación estequiométrica 2:2 entre H₂ y H₂O, así que 4 moles H₂ → 4 moles H₂O." },
    { text: "El proceso por el cual un sólido pasa directamente al estado gaseoso se llama",
      options: ["fusión", "evaporación", "sublimación", "condensación"],
      correct: 2,
      explanation: "Sublimación: sólido → gas (ej. hielo seco, naftalina)." },
    { text: "Los puentes de hidrógeno son particularmente fuertes cuando el H está unido a átomos de",
      options: ["C, S, Cl", "F, O, N", "Na, K, Ca", "Br, I, P"],
      correct: 1,
      explanation: "Los puentes de H requieren átomos pequeños y muy electronegativos: F, O, N." },
    { text: "Una reacción exotérmica se caracteriza porque",
      options: ["absorbe energía del entorno.", "libera energía al entorno.", "no involucra energía.", "es siempre espontánea."],
      correct: 1,
      explanation: "Exotérmica = libera energía (ΔH < 0). Endotérmica = absorbe." },
    { text: "El grupo funcional —OH presente en un compuesto orgánico identifica a un",
      options: ["aldehído", "alcohol", "ácido carboxílico", "éter"],
      correct: 1,
      explanation: "El grupo hidroxilo —OH unido a un carbono saturado define a un alcohol (R—OH)." },
    { text: "El metano (CH₄) es el alcano más",
      options: ["pesado", "complejo", "simple", "polar"],
      correct: 2,
      explanation: "CH₄ es el alcano más simple, con sólo 1 carbono." },
    { text: "¿Cuál es el grupo funcional del ácido acético?",
      options: ["—OH", "—CHO", "—COOH", "—NH₂"],
      correct: 2,
      explanation: "El grupo carboxilo —COOH define a los ácidos carboxílicos (CH₃—COOH = ácido acético)." },
    { text: "El benceno (C₆H₆) es un hidrocarburo",
      options: ["alifático saturado.", "alifático insaturado.", "aromático.", "alicíclico."],
      correct: 2,
      explanation: "Benceno: anillo de 6 carbonos con sistema π deslocalizado → aromático." },
    { text: "La reacción de un ácido y una base para formar sal y agua se llama",
      options: ["combustión", "neutralización", "oxidación", "polimerización"],
      correct: 1,
      explanation: "Ácido + Base → Sal + H₂O = neutralización." },
    { text: "¿Qué propiedad NO es coligativa?",
      options: ["aumento ebulloscópico", "descenso crioscópico", "color de la disolución", "presión osmótica"],
      correct: 2,
      explanation: "Las coligativas dependen del número de partículas: aumento ebull., descenso crio., presión osmótica, descenso de presión de vapor. El color depende del tipo de soluto." },
    { text: "El catalizador en una reacción química",
      options: ["se consume durante la reacción.", "cambia el equilibrio químico.", "disminuye la energía de activación.", "aumenta la entalpía de la reacción."],
      correct: 2,
      explanation: "El catalizador baja la Ea y acelera la reacción, pero no se consume ni cambia el equilibrio." },
    { text: "Las proteínas están formadas por",
      options: ["nucleótidos", "monosacáridos", "ácidos grasos", "aminoácidos"],
      correct: 3,
      explanation: "Los aminoácidos son los monómeros de las proteínas. Se unen por enlaces peptídicos." },
    { text: "¿Cuál es la fórmula molecular del dióxido de carbono?",
      options: ["CO", "CO₂", "C₂O", "C₂O₂"],
      correct: 1,
      explanation: "Dióxido = 2 átomos de oxígeno → CO₂." },
    { text: "El estado de oxidación del oxígeno en el agua (H₂O) es",
      options: ["+2", "+1", "−2", "−1"],
      correct: 2,
      explanation: "El O normalmente tiene estado de oxidación −2 (excepto en peróxidos y con flúor)." },
  ],

  biologia: [
    { text: "La teoría celular postula que",
      options: ["sólo los animales están formados por células.", "todos los seres vivos están formados por células.", "las células surgen espontáneamente del aire.", "las plantas no son organismos celulares."],
      correct: 1,
      explanation: "Postulados: todos los seres vivos están formados por células, la célula es la unidad de vida y toda célula proviene de otra preexistente." },
    { text: "El organelo encargado de la fotosíntesis es",
      options: ["la mitocondria", "el ribosoma", "el cloroplasto", "el aparato de Golgi"],
      correct: 2,
      explanation: "El cloroplasto contiene clorofila y realiza la fotosíntesis (presente sólo en células vegetales)." },
    { text: "El material genético en los organismos eucariontes se encuentra principalmente en",
      options: ["el citoplasma", "el núcleo", "los ribosomas", "el retículo endoplásmico"],
      correct: 1,
      explanation: "El DNA en eucariontes está organizado en cromosomas dentro del núcleo." },
    { text: "La fotosíntesis produce",
      options: ["CO₂ y H₂O", "glucosa y O₂", "ATP y CO₂", "proteínas y O₂"],
      correct: 1,
      explanation: "Fórmula: 6CO₂ + 6H₂O + luz → C₆H₁₂O₆ + 6O₂." },
    { text: "La glucólisis es un proceso que ocurre en",
      options: ["la mitocondria", "el citoplasma", "el cloroplasto", "el núcleo"],
      correct: 1,
      explanation: "La glucólisis (glucosa → 2 piruvato) sucede en el citoplasma, antes del ciclo de Krebs." },
    { text: "El ciclo de Krebs ocurre en",
      options: ["la matriz mitocondrial", "el citoplasma", "el cloroplasto", "el núcleo"],
      correct: 0,
      explanation: "El ciclo del ácido cítrico (Krebs) tiene lugar en la matriz mitocondrial de eucariontes." },
    { text: "El producto final de la respiración celular aerobia es",
      options: ["ácido láctico", "etanol", "CO₂ y H₂O", "glucosa"],
      correct: 2,
      explanation: "Respiración aerobia: glucosa + O₂ → CO₂ + H₂O + ATP." },
    { text: "El número de moléculas de ATP producidas por una molécula de glucosa en la respiración aerobia es aproximadamente",
      options: ["2", "8", "18", "36"],
      correct: 3,
      explanation: "La respiración aerobia produce ~36-38 ATP por glucosa (glucólisis + Krebs + cadena respiratoria)." },
    { text: "Las enzimas son sustancias de naturaleza",
      options: ["lipídica", "proteica", "glucídica", "mineral"],
      correct: 1,
      explanation: "Las enzimas son proteínas catalíticas (excepto algunos ribozimas, que son RNA)." },
    { text: "El ADN está formado por nucleótidos cuyas bases nitrogenadas son",
      options: ["adenina, timina, guanina y citosina", "adenina, uracilo, guanina y citosina", "adenina, timina, guanina y uracilo", "adenina, uracilo, citosina y timina"],
      correct: 0,
      explanation: "ADN: A, T, G, C. ARN: A, U, G, C (uracilo en lugar de timina)." },
    { text: "El emparejamiento correcto de bases nitrogenadas en el ADN es",
      options: ["A-G y T-C", "A-T y G-C", "A-C y G-T", "A-U y G-C"],
      correct: 1,
      explanation: "Por puentes de hidrógeno: A=T (2 enlaces) y G≡C (3 enlaces)." },
    { text: "El proceso por el cual el ADN se duplica antes de la división celular se llama",
      options: ["transcripción", "traducción", "replicación", "mitosis"],
      correct: 2,
      explanation: "Replicación: ADN → ADN. Transcripción: ADN → ARN. Traducción: ARN → proteína." },
    { text: "La meiosis produce, a partir de una célula diploide,",
      options: ["2 células diploides", "4 células haploides", "4 células diploides", "2 células haploides"],
      correct: 1,
      explanation: "Meiosis: 1 célula diploide (2n) → 4 células haploides (n) → forma gametos." },
    { text: "Una mujer con genotipo XᴮXᵇ y un hombre XᴮY (B = visión normal, b = daltonismo recesivo). La probabilidad de tener un hijo varón daltónico es",
      options: ["0%", "25%", "50%", "100%"],
      correct: 1,
      explanation: "Hijos varones: 50% XᴮY (sano) y 50% XᵇY (daltónico). Del total: 25% varones daltónicos." },
    { text: "La unidad funcional de la herencia se llama",
      options: ["alelo", "gen", "cromosoma", "ribosoma"],
      correct: 1,
      explanation: "El gen es la unidad funcional/molecular de la herencia. Un alelo es una variante de un gen." },
    { text: "Las bacterias son organismos",
      options: ["eucariontes", "procariontes", "pluricelulares", "virales"],
      correct: 1,
      explanation: "Las bacterias carecen de núcleo definido y organelos membranosos: son procariontes." },
    { text: "El proceso evolutivo postulado por Darwin se basa en",
      options: ["la herencia de los caracteres adquiridos.", "la selección natural.", "la creación divina.", "el uso y desuso de los órganos."],
      correct: 1,
      explanation: "Darwin: selección natural (los más aptos sobreviven y reproducen). Lamarck postuló herencia de caracteres adquiridos." },
    { text: "La función de los anticuerpos en el sistema inmunológico es",
      options: ["producir hormonas", "reconocer y neutralizar antígenos extraños", "transportar oxígeno", "almacenar energía"],
      correct: 1,
      explanation: "Los anticuerpos (inmunoglobulinas) reconocen específicamente antígenos y los neutralizan." },
    { text: "El órgano que produce la insulina en el cuerpo humano es",
      options: ["el hígado", "el páncreas", "el riñón", "la tiroides"],
      correct: 1,
      explanation: "El páncreas (células β de los islotes de Langerhans) produce insulina, que regula la glucosa en sangre." },
    { text: "¿Cuál es la unidad estructural y funcional del riñón?",
      options: ["la neurona", "la nefrona", "el alvéolo", "el hepatocito"],
      correct: 1,
      explanation: "La nefrona es la unidad funcional del riñón, encargada de filtrar la sangre y formar orina." },
    { text: "El intercambio de gases en los pulmones ocurre en",
      options: ["los bronquios", "la tráquea", "los alvéolos pulmonares", "la faringe"],
      correct: 2,
      explanation: "Los alvéolos son las pequeñas bolsas donde se realiza el intercambio O₂/CO₂ con la sangre." },
    { text: "La sucesión ecológica primaria comienza en",
      options: ["un bosque maduro", "un terreno sin suelo previo (lava, roca)", "un cultivo abandonado", "un río contaminado"],
      correct: 1,
      explanation: "Primaria: empieza desde cero (sin suelo previo, ej. tras erupción volcánica). Secundaria: parte de un suelo ya existente." },
    { text: "El nivel trófico de los herbívoros corresponde al de",
      options: ["productores", "consumidores primarios", "consumidores secundarios", "descomponedores"],
      correct: 1,
      explanation: "Productores: plantas. Consumidores primarios: herbívoros. Secundarios: carnívoros que comen herbívoros." },
    { text: "El ciclo del agua incluye los procesos de",
      options: ["evaporación, condensación y precipitación.", "respiración, fotosíntesis y fermentación.", "nitrificación, desnitrificación y amonificación.", "polinización, fertilización y germinación."],
      correct: 0,
      explanation: "Ciclo hidrológico: evaporación → condensación (nubes) → precipitación (lluvia) → escurrimiento → vuelve al ciclo." },
    { text: "El reino al que pertenecen las algas, los protozoarios y otros organismos eucariontes simples es",
      options: ["Monera", "Protista", "Fungi", "Plantae"],
      correct: 1,
      explanation: "Reino Protista: eucariontes simples y heterogéneos (algas, protozoarios, mohos acuáticos)." },
  ],

  historiaUniversal: [
    { text: "La Revolución Francesa inició en el año",
      options: ["1776", "1789", "1804", "1815"],
      correct: 1,
      explanation: "Toma de la Bastilla: 14 de julio de 1789. 1776: Independencia de EE.UU. 1815: Congreso de Viena." },
    { text: "El lema de la Revolución Francesa fue",
      options: ["\"Pan, paz y tierra\"", "\"Libertad, igualdad y fraternidad\"", "\"Democracia o muerte\"", "\"Patria o libertad\""],
      correct: 1,
      explanation: "El triángulo revolucionario republicano: liberté, égalité, fraternité." },
    { text: "El periodo de la historia que va aproximadamente del siglo V al XV se conoce como",
      options: ["Edad Antigua", "Edad Media", "Edad Moderna", "Edad Contemporánea"],
      correct: 1,
      explanation: "Edad Media: caída del Imperio Romano de Occidente (476) a la caída de Constantinopla (1453) o descubrimiento de América (1492)." },
    { text: "La Reforma Protestante fue iniciada en 1517 por",
      options: ["Juan Calvino", "Enrique VIII", "Martín Lutero", "Erasmo de Rotterdam"],
      correct: 2,
      explanation: "Martín Lutero clavó sus 95 tesis en Wittenberg en 1517, iniciando la Reforma." },
    { text: "El monarca francés ejecutado durante la Revolución Francesa fue",
      options: ["Luis XIV", "Luis XV", "Luis XVI", "Luis XVIII"],
      correct: 2,
      explanation: "Luis XVI fue guillotinado el 21 de enero de 1793 durante la Revolución." },
    { text: "Napoleón Bonaparte fue derrotado definitivamente en la batalla de",
      options: ["Austerlitz", "Trafalgar", "Waterloo", "Leipzig"],
      correct: 2,
      explanation: "Waterloo, 18 de junio de 1815. Fue desterrado a Santa Elena tras esta derrota." },
    { text: "La Revolución Industrial comenzó en",
      options: ["Francia", "Alemania", "Inglaterra", "Estados Unidos"],
      correct: 2,
      explanation: "La Revolución Industrial inició en Inglaterra a mediados del siglo XVIII (textiles, máquina de vapor)." },
    { text: "Karl Marx y Friedrich Engels publicaron en 1848",
      options: ["El capital", "El manifiesto comunista", "La riqueza de las naciones", "Los miserables"],
      correct: 1,
      explanation: "El Manifiesto del Partido Comunista (1848). El Capital (vol. I) se publicó en 1867." },
    { text: "La Primera Guerra Mundial estalló tras",
      options: ["la invasión a Polonia.", "el asesinato del archiduque Francisco Fernando.", "el ataque a Pearl Harbor.", "la caída del Muro de Berlín."],
      correct: 1,
      explanation: "El detonante fue el asesinato de Francisco Fernando de Austria en Sarajevo (28 jun 1914)." },
    { text: "El tratado que puso fin a la Primera Guerra Mundial fue el de",
      options: ["Versalles", "Tordesillas", "Westfalia", "Brest-Litovsk"],
      correct: 0,
      explanation: "El Tratado de Versalles (1919) impuso fuertes sanciones a Alemania, sembrando descontento que llevaría a WWII." },
    { text: "La Revolución Rusa de 1917 fue liderada por los",
      options: ["fascistas", "bolcheviques", "girondinos", "jacobinos"],
      correct: 1,
      explanation: "Los bolcheviques (ala mayoritaria del POSDR), encabezados por Lenin, tomaron el poder en octubre de 1917." },
    { text: "La Segunda Guerra Mundial inició con la invasión alemana a",
      options: ["Francia", "Polonia", "Austria", "Checoslovaquia"],
      correct: 1,
      explanation: "1 de septiembre de 1939: invasión de Polonia. Reino Unido y Francia declaran la guerra a Alemania el 3 de septiembre." },
    { text: "Estados Unidos entró en la Segunda Guerra Mundial tras",
      options: ["la invasión a Polonia.", "el ataque a Pearl Harbor.", "la caída de París.", "la batalla de Stalingrado."],
      correct: 1,
      explanation: "Pearl Harbor, 7 de diciembre de 1941. EE.UU. declara la guerra a Japón al día siguiente." },
    { text: "Las bombas atómicas lanzadas en la Segunda Guerra Mundial fueron arrojadas sobre",
      options: ["Tokio y Osaka", "Hiroshima y Nagasaki", "Berlín y Dresde", "Pyongyang y Seúl"],
      correct: 1,
      explanation: "Hiroshima (6 ago 1945) y Nagasaki (9 ago 1945)." },
    { text: "La organización internacional creada al finalizar la Segunda Guerra Mundial es",
      options: ["la Sociedad de Naciones", "la Organización de las Naciones Unidas", "la Unión Europea", "el Pacto de Varsovia"],
      correct: 1,
      explanation: "ONU fundada en 1945, reemplazó a la Sociedad de Naciones (que existió entre WWI y WWII)." },
    { text: "El Muro de Berlín cayó en el año",
      options: ["1989", "1991", "1985", "1995"],
      correct: 0,
      explanation: "9 de noviembre de 1989, marcando el inicio del fin de la Guerra Fría." },
    { text: "La Unión Soviética se disolvió oficialmente en",
      options: ["1989", "1990", "1991", "1993"],
      correct: 2,
      explanation: "El 26 de diciembre de 1991 se disolvió oficialmente la URSS." },
    { text: "El sistema económico característico del bloque occidental durante la Guerra Fría era el",
      options: ["socialismo", "feudalismo", "capitalismo", "mercantilismo"],
      correct: 2,
      explanation: "Bloque occidental (EE.UU., Europa Occidental): capitalismo. Bloque oriental (URSS y aliados): socialismo de Estado." },
    { text: "John Locke es considerado uno de los principales pensadores del",
      options: ["Romanticismo", "Liberalismo", "Marxismo", "Existencialismo"],
      correct: 1,
      explanation: "Locke (siglo XVII) defendió la división de poderes, los derechos naturales y el contrato social: base del liberalismo político." },
    { text: "El imperialismo del siglo XIX se caracterizó por",
      options: ["la independencia masiva de colonias.", "la expansión y dominación de territorios por potencias industriales.", "el fin del comercio internacional.", "la unificación democrática del mundo."],
      correct: 1,
      explanation: "Las potencias europeas (más Japón y EE.UU.) repartieron África y Asia entre 1870-1914 buscando materias primas y mercados." },
    { text: "El Renacimiento se originó en",
      options: ["Francia, siglo XIV.", "Italia, siglos XIV-XV.", "Alemania, siglo XVI.", "España, siglo XV."],
      correct: 1,
      explanation: "Renacimiento: Italia, especialmente Florencia, finales del siglo XIV hasta el XVI." },
    { text: "La Guerra de Corea (1950-1953) fue un conflicto que enfrentó indirectamente a",
      options: ["Estados Unidos y la Unión Soviética", "Inglaterra y Francia", "Alemania y Japón", "China y la India"],
      correct: 0,
      explanation: "Guerra Fría: EE.UU. (ONU) respaldó a Corea del Sur; URSS y China apoyaron a Corea del Norte." },
    { text: "Adolf Hitler ascendió al poder en Alemania en el año",
      options: ["1923", "1933", "1939", "1945"],
      correct: 1,
      explanation: "Hitler fue nombrado canciller del Reich el 30 de enero de 1933." },
    { text: "El movimiento de derechos civiles en EE.UU. encabezado por Martin Luther King Jr. tuvo lugar principalmente en la década de los",
      options: ["1940s", "1950s y 1960s", "1970s", "1980s"],
      correct: 1,
      explanation: "Las décadas de 1950 y 1960. Su famoso discurso \"I have a dream\" fue en 1963." },
    { text: "La Revolución China que llevó al poder a Mao Zedong triunfó en",
      options: ["1917", "1936", "1949", "1959"],
      correct: 2,
      explanation: "El 1 de octubre de 1949 se proclamó la República Popular China tras la victoria comunista." },
  ],

  historiaMexico: [
    { text: "La cultura madre de Mesoamérica, considerada la más antigua, fue la",
      options: ["maya", "azteca", "olmeca", "teotihuacana"],
      correct: 2,
      explanation: "Los olmecas (1500-400 a.C.) son considerados la cultura madre por sus aportaciones a culturas posteriores." },
    { text: "El gobernante mexica que recibió a Hernán Cortés en Tenochtitlan en 1519 fue",
      options: ["Cuitláhuac", "Cuauhtémoc", "Moctezuma II", "Axayácatl"],
      correct: 2,
      explanation: "Moctezuma Xocoyotzin (Moctezuma II) era el tlatoani mexica al momento de la llegada de los españoles." },
    { text: "La caída de México-Tenochtitlan ante los españoles ocurrió en",
      options: ["1492", "1519", "1521", "1535"],
      correct: 2,
      explanation: "13 de agosto de 1521 cayó Tenochtitlan tras 75 días de sitio." },
    { text: "El primer virrey de la Nueva España fue",
      options: ["Hernán Cortés", "Antonio de Mendoza", "Luis de Velasco", "Diego Velázquez"],
      correct: 1,
      explanation: "Antonio de Mendoza gobernó como primer virrey de 1535 a 1550." },
    { text: "La Independencia de México inició el 16 de septiembre de 1810 con el grito de",
      options: ["Allende", "Aldama", "Hidalgo", "Morelos"],
      correct: 2,
      explanation: "Miguel Hidalgo dio el Grito de Dolores en la madrugada del 16 de septiembre de 1810." },
    { text: "El documento \"Sentimientos de la Nación\" fue presentado en 1813 por",
      options: ["Miguel Hidalgo", "José María Morelos", "Vicente Guerrero", "Agustín de Iturbide"],
      correct: 1,
      explanation: "Morelos lo presentó en el Congreso de Anáhuac en Chilpancingo el 14 de septiembre de 1813." },
    { text: "La consumación de la Independencia de México ocurrió en",
      options: ["1810", "1813", "1821", "1824"],
      correct: 2,
      explanation: "27 de septiembre de 1821, con la entrada del Ejército Trigarante a la Ciudad de México." },
    { text: "El primer presidente de México fue",
      options: ["Agustín de Iturbide", "Vicente Guerrero", "Guadalupe Victoria", "Antonio López de Santa Anna"],
      correct: 2,
      explanation: "Guadalupe Victoria fue el primer presidente del México independiente (1824-1829). Iturbide fue emperador, no presidente." },
    { text: "El presidente que promulgó las Leyes de Reforma fue",
      options: ["Antonio López de Santa Anna", "Benito Juárez", "Porfirio Díaz", "Francisco I. Madero"],
      correct: 1,
      explanation: "Benito Juárez impulsó las Leyes de Reforma (1859-1863) que separaron Iglesia y Estado." },
    { text: "El emperador francés que intentó instaurar un imperio en México en el siglo XIX fue",
      options: ["Napoleón I", "Napoleón III", "Maximiliano I", "Luis Felipe"],
      correct: 1,
      explanation: "Napoleón III envió tropas en 1862; el archiduque Maximiliano de Habsburgo fue impuesto como emperador (1864-1867)." },
    { text: "La batalla del 5 de mayo de 1862 en Puebla enfrentó al ejército mexicano contra el",
      options: ["estadounidense", "francés", "español", "inglés"],
      correct: 1,
      explanation: "El general Zaragoza venció al ejército francés en Puebla durante la Segunda Intervención." },
    { text: "El Porfiriato fue el periodo gobernado por Porfirio Díaz entre",
      options: ["1854-1876", "1876-1911", "1900-1920", "1880-1900"],
      correct: 1,
      explanation: "Porfirio Díaz gobernó entre 1876 y 1911 (con un breve intervalo de Manuel González 1880-1884)." },
    { text: "La Revolución Mexicana inició con el Plan de San Luis convocado por",
      options: ["Emiliano Zapata", "Francisco Villa", "Francisco I. Madero", "Venustiano Carranza"],
      correct: 2,
      explanation: "Madero proclamó el Plan de San Luis llamando al levantamiento el 20 de noviembre de 1910." },
    { text: "El lema \"Tierra y libertad\" se asocia con",
      options: ["Francisco Villa", "Emiliano Zapata", "Venustiano Carranza", "Álvaro Obregón"],
      correct: 1,
      explanation: "Lema del zapatismo, defensor de la restitución de tierras a campesinos (Plan de Ayala, 1911)." },
    { text: "La Constitución Política vigente de México fue promulgada en",
      options: ["1857", "1910", "1917", "1924"],
      correct: 2,
      explanation: "Constitución de 1917 promulgada el 5 de febrero por Venustiano Carranza." },
    { text: "El Artículo 27 de la Constitución de 1917 estableció",
      options: ["el voto universal.", "la propiedad de la nación sobre tierras y aguas.", "la educación laica.", "la libertad de prensa."],
      correct: 1,
      explanation: "Art. 27: la propiedad originaria de tierras y aguas pertenece a la Nación, base de la reforma agraria." },
    { text: "El presidente que expropió el petróleo mexicano en 1938 fue",
      options: ["Plutarco Elías Calles", "Lázaro Cárdenas", "Manuel Ávila Camacho", "Miguel Alemán"],
      correct: 1,
      explanation: "Lázaro Cárdenas decretó la Expropiación Petrolera el 18 de marzo de 1938." },
    { text: "El sexenio de Manuel Ávila Camacho (1940-1946) coincidió con",
      options: ["la Revolución Mexicana", "la Segunda Guerra Mundial", "la Guerra Fría plena", "el terremoto del 85"],
      correct: 1,
      explanation: "México declaró la guerra al Eje en 1942 y participó con el Escuadrón 201 en el Pacífico." },
    { text: "El movimiento estudiantil de 1968 culminó trágicamente en",
      options: ["el Zócalo de la CDMX", "la Plaza de las Tres Culturas (Tlatelolco)", "Ciudad Universitaria", "Xochimilco"],
      correct: 1,
      explanation: "La masacre del 2 de octubre de 1968 ocurrió en la Plaza de las Tres Culturas en Tlatelolco." },
    { text: "El presidente bajo cuyo mandato se firmó el TLCAN (1994) fue",
      options: ["Carlos Salinas de Gortari", "Ernesto Zedillo", "Vicente Fox", "Miguel de la Madrid"],
      correct: 0,
      explanation: "Salinas firmó el TLCAN; entró en vigor el 1 de enero de 1994 al final de su sexenio." },
    { text: "El año en que se rompió la hegemonía de un solo partido en la Presidencia de México fue",
      options: ["1988", "1994", "2000", "2006"],
      correct: 2,
      explanation: "En 2000, Vicente Fox del PAN ganó la presidencia, terminando 71 años de gobiernos del PRI." },
    { text: "El Plan de Iguala (1821) proclamó las llamadas \"Tres Garantías\":",
      options: ["independencia, religión y unión.", "libertad, igualdad y fraternidad.", "tierra, libertad y justicia.", "democracia, federación y república."],
      correct: 0,
      explanation: "Las Tres Garantías: religión católica, independencia de España y unión entre todos los habitantes." },
    { text: "La cultura mexica fundó México-Tenochtitlan en el año",
      options: ["1325", "1492", "1521", "1200"],
      correct: 0,
      explanation: "La fundación tradicional de Tenochtitlan se ubica en 1325, en un islote del lago de Texcoco." },
    { text: "El Tratado de Guadalupe-Hidalgo (1848) significó para México",
      options: ["la pérdida de más de la mitad de su territorio.", "la independencia política total.", "la incorporación de Centroamérica.", "la creación del Distrito Federal."],
      correct: 0,
      explanation: "México cedió Alta California, Nuevo México, Arizona, Nevada, Utah y partes de otros estados a EE.UU." },
    { text: "El movimiento cristero (1926-1929) fue un conflicto principalmente entre",
      options: ["liberales y conservadores.", "el gobierno federal y católicos.", "obreros y patrones.", "campesinos y hacendados."],
      correct: 1,
      explanation: "Conflicto armado entre el gobierno de Plutarco Elías Calles (anticlerical) y católicos en defensa del culto religioso." },
  ],

  literatura: [
    { text: "El género literario que se caracteriza por narrar acontecimientos en prosa y de extensión variable es",
      options: ["lírico", "dramático", "narrativo", "épico"],
      correct: 2,
      explanation: "Narrativo: género que cuenta hechos reales o ficticios en prosa (cuento, novela)." },
    { text: "Una obra escrita en verso y de carácter musical pertenece al género",
      options: ["lírico", "épico", "dramático", "ensayístico"],
      correct: 0,
      explanation: "Lírico: expresión de sentimientos en verso (poemas, odas, sonetos)." },
    { text: "El subgénero narrativo extenso, con múltiples personajes y tramas, es",
      options: ["la fábula", "el cuento", "la novela", "el epigrama"],
      correct: 2,
      explanation: "Novela: narración extensa con desarrollo amplio de personajes y tramas (Don Quijote, Cien años de soledad)." },
    { text: "La principal característica del cuento es",
      options: ["su gran extensión y múltiples tramas.", "su brevedad y desarrollo de una sola trama.", "estar siempre escrito en verso.", "carecer de personajes."],
      correct: 1,
      explanation: "El cuento es breve, con trama única y final concentrado (Cortázar definió: \"se gana por knockout\")." },
    { text: "Don Quijote de la Mancha fue escrita por",
      options: ["Lope de Vega", "Francisco de Quevedo", "Miguel de Cervantes Saavedra", "Calderón de la Barca"],
      correct: 2,
      explanation: "Cervantes publicó la primera parte en 1605 y la segunda en 1615." },
    { text: "La corriente literaria que privilegia la subjetividad, la naturaleza y la libertad creativa es",
      options: ["Clasicismo", "Romanticismo", "Realismo", "Naturalismo"],
      correct: 1,
      explanation: "Romanticismo (siglo XIX): exaltación del yo, sentimientos, libertad, lo nocturno y lo sublime." },
    { text: "El Naturalismo, derivado del Realismo, fue impulsado en Francia por",
      options: ["Victor Hugo", "Émile Zola", "Honoré de Balzac", "Marcel Proust"],
      correct: 1,
      explanation: "Émile Zola fundó el Naturalismo aplicando método científico a la novela (Germinal, Nana)." },
    { text: "El Boom Latinoamericano de los años 60 incluye a autores como",
      options: ["Borges, Sábato y Lorca", "García Márquez, Cortázar, Vargas Llosa y Fuentes", "Cervantes, Lope y Quevedo", "Neruda, Mistral y Octavio Paz"],
      correct: 1,
      explanation: "Boom Latinoamericano: novela hispanoamericana de los 60. García Márquez (col), Cortázar (arg), Vargas Llosa (per), Fuentes (mex)." },
    { text: "Pablo Neruda fue un poeta de nacionalidad",
      options: ["mexicana", "argentina", "chilena", "uruguaya"],
      correct: 2,
      explanation: "Neruda (1904-1973), poeta chileno, Premio Nobel de Literatura en 1971." },
    { text: "El género dramático se caracteriza por",
      options: ["narrar en tercera persona.", "estar destinado a ser representado en escena.", "expresar sentimientos en verso.", "argumentar una tesis."],
      correct: 1,
      explanation: "Dramático: obra construida para representarse, con diálogos y acotaciones." },
    { text: "La tragedia griega tiene como autores clásicos a",
      options: ["Homero y Hesíodo", "Esquilo, Sófocles y Eurípides", "Aristóteles y Platón", "Píndaro y Safo"],
      correct: 1,
      explanation: "Los tres grandes trágicos griegos del siglo V a.C.: Esquilo, Sófocles (Edipo Rey) y Eurípides (Medea)." },
    { text: "El recurso literario que consiste en atribuir cualidades humanas a objetos o animales se llama",
      options: ["hipérbole", "metáfora", "personificación", "anáfora"],
      correct: 2,
      explanation: "Personificación o prosopopeya: dar características humanas a lo no humano (\"el viento susurra\")." },
    { text: "La metáfora consiste en",
      options: ["comparar dos elementos usando \"como\".", "identificar un elemento con otro por semejanza, sin nexo.", "repetir palabras al inicio de versos.", "exagerar una cualidad."],
      correct: 1,
      explanation: "Metáfora: sustitución directa (\"sus ojos son dos luceros\"). El símil sí usa \"como\"." },
    { text: "Edipo Rey, obra clave del teatro clásico, fue escrita por",
      options: ["Esquilo", "Sófocles", "Eurípides", "Aristófanes"],
      correct: 1,
      explanation: "Edipo Rey (c. 429 a.C.) es de Sófocles. Aristóteles la consideró modelo de tragedia perfecta." },
    { text: "La obra \"Cien años de soledad\" pertenece a",
      options: ["Mario Vargas Llosa", "Gabriel García Márquez", "Julio Cortázar", "Jorge Luis Borges"],
      correct: 1,
      explanation: "García Márquez publicó la novela en 1967. Es la cumbre del realismo mágico." },
    { text: "La rima en la que coinciden todos los sonidos a partir de la última vocal acentuada se llama",
      options: ["asonante", "consonante", "interna", "libre"],
      correct: 1,
      explanation: "Consonante: coinciden todos los fonemas. Asonante: sólo las vocales (más laxa)." },
    { text: "El soneto se compone de",
      options: ["dos cuartetos y dos tercetos", "tres cuartetos y un terceto", "cuatro cuartetos", "ocho octavas"],
      correct: 0,
      explanation: "Soneto clásico (Petrarca, Garcilaso): 14 versos en 2 cuartetos + 2 tercetos." },
    { text: "Sor Juana Inés de la Cruz vivió en",
      options: ["el siglo XV", "el siglo XVII (Barroco)", "el siglo XIX (Romanticismo)", "el siglo XX"],
      correct: 1,
      explanation: "Sor Juana (1648-1695) fue figura central del Barroco novohispano." },
    { text: "La obra \"Pedro Páramo\" es considerada una de las grandes novelas mexicanas y fue escrita por",
      options: ["Octavio Paz", "Juan Rulfo", "Carlos Fuentes", "Mariano Azuela"],
      correct: 1,
      explanation: "Juan Rulfo publicó Pedro Páramo en 1955. Una obra fundamental del realismo mágico." },
    { text: "El término diéresis se refiere a",
      options: ["la separación de dos vocales en sílabas distintas.", "la unión de dos vocales en una sílaba.", "el acento en la sílaba final.", "la repetición de palabras."],
      correct: 0,
      explanation: "Diéresis: ruptura forzada de un diptongo, indicada con \"¨\" (rü-i-do). Sinéresis es lo opuesto." },
    { text: "La fábula es un subgénero que se caracteriza por",
      options: ["su extensión amplia y trama compleja.", "ser una narración breve con moraleja y personajes a menudo animales.", "estar siempre escrita en verso libre.", "no tener un final didáctico."],
      correct: 1,
      explanation: "Fábula: relato corto con animales antropomorfizados que ilustra una enseñanza moral (Esopo, La Fontaine)." },
    { text: "El verso libre se caracteriza por",
      options: ["seguir un esquema métrico fijo.", "rimar siempre en consonante.", "no estar sujeto a métrica ni rima reguladas.", "tener exactamente 11 sílabas."],
      correct: 2,
      explanation: "Verso libre: prescinde de medida y rima fijas; busca ritmo desde otros recursos." },
    { text: "El ensayo es un género",
      options: ["narrativo de extensión amplia.", "argumentativo en prosa, que expone una idea personal.", "dramático en verso.", "lírico siempre breve."],
      correct: 1,
      explanation: "Ensayo: género en prosa donde un autor expone su pensamiento sobre un tema (Montaigne, Octavio Paz)." },
    { text: "La obra \"El laberinto de la soledad\" es de",
      options: ["Carlos Fuentes", "Octavio Paz", "Alfonso Reyes", "Juan Rulfo"],
      correct: 1,
      explanation: "Ensayo de Octavio Paz publicado en 1950 sobre la identidad mexicana." },
    { text: "En literatura, el narrador omnisciente es aquel que",
      options: ["forma parte de la historia como personaje.", "narra sólo lo que ve y oye.", "conoce todo lo que sucede, incluidos pensamientos de los personajes.", "se dirige directamente al lector en segunda persona."],
      correct: 2,
      explanation: "Narrador omnisciente: tercera persona, sabe todo de los personajes (incluso lo que piensan o sienten)." },
  ],

  geografia: [
    { text: "La línea imaginaria que divide al planeta en hemisferios Norte y Sur es",
      options: ["el meridiano de Greenwich", "el ecuador", "el trópico de Cáncer", "el trópico de Capricornio"],
      correct: 1,
      explanation: "El Ecuador es el paralelo 0° y divide al planeta en hemisferio Norte y Sur." },
    { text: "El meridiano de Greenwich se utiliza como referencia para",
      options: ["las estaciones del año", "los husos horarios", "la temperatura promedio", "la altitud"],
      correct: 1,
      explanation: "Greenwich (0° de longitud) define el Tiempo Universal Coordinado (UTC) y los husos horarios." },
    { text: "El continente más grande en superficie es",
      options: ["África", "América", "Asia", "Europa"],
      correct: 2,
      explanation: "Asia ocupa unos 44.6 millones de km², el continente más extenso." },
    { text: "El océano más extenso es el",
      options: ["Atlántico", "Pacífico", "Índico", "Ártico"],
      correct: 1,
      explanation: "El Pacífico (~165 millones km²) cubre cerca de un tercio de la superficie terrestre." },
    { text: "La capa terrestre sobre la que se asientan los continentes es",
      options: ["el núcleo externo", "el manto inferior", "la corteza", "la mesosfera"],
      correct: 2,
      explanation: "La corteza terrestre es la capa más externa y delgada; en ella se asientan continentes y océanos." },
    { text: "México se encuentra geográficamente en la placa",
      options: ["Sudamericana", "Norteamericana", "Africana", "Euroasiática"],
      correct: 1,
      explanation: "El territorio mexicano se asienta principalmente sobre la placa Norteamericana." },
    { text: "El \"Cinturón de Fuego del Pacífico\" se caracteriza por",
      options: ["su gran cantidad de desiertos.", "su alta actividad volcánica y sísmica.", "sus extensas selvas tropicales.", "su clima frío extremo."],
      correct: 1,
      explanation: "Bordea la cuenca del Pacífico y concentra ~75% de los volcanes y la mayoría de los sismos del mundo." },
    { text: "El volcán activo más alto de México es",
      options: ["Popocatépetl", "Iztaccíhuatl", "Pico de Orizaba", "Paricutín"],
      correct: 2,
      explanation: "El Pico de Orizaba (Citlaltépetl, 5,636 m) es la montaña más alta de México." },
    { text: "El estado mexicano con mayor extensión territorial es",
      options: ["Sonora", "Chihuahua", "Coahuila", "Oaxaca"],
      correct: 1,
      explanation: "Chihuahua: ~247,000 km², el estado más grande de México." },
    { text: "La capital del Estado de Yucatán es",
      options: ["Cancún", "Mérida", "Campeche", "Valladolid"],
      correct: 1,
      explanation: "Mérida es la capital del estado de Yucatán; Cancún está en Quintana Roo." },
    { text: "El principal río de México por su extensión es el",
      options: ["Lerma", "Pánuco", "Bravo", "Balsas"],
      correct: 2,
      explanation: "El río Bravo (Río Grande) marca la frontera norte y es el más largo (~3,000 km)." },
    { text: "La región natural caracterizada por baja temperatura, escasa vegetación y suelos congelados es",
      options: ["la sabana", "la taiga", "la tundra", "la pradera"],
      correct: 2,
      explanation: "Tundra: bioma de altas latitudes/montañas con permafrost, musgos y líquenes." },
    { text: "El recurso natural NO renovable es",
      options: ["el agua dulce", "el viento", "el petróleo", "la energía solar"],
      correct: 2,
      explanation: "El petróleo se formó durante millones de años; su agotamiento es a escala geológica. Es no renovable." },
    { text: "El principal estado productor de plata en México es",
      options: ["Sonora", "Zacatecas", "Chihuahua", "Veracruz"],
      correct: 1,
      explanation: "Zacatecas es históricamente el mayor productor mundial y nacional de plata." },
    { text: "La capa atmosférica donde ocurren los fenómenos meteorológicos es",
      options: ["la estratosfera", "la troposfera", "la mesosfera", "la termosfera"],
      correct: 1,
      explanation: "La troposfera (0-12 km) contiene casi todo el vapor de agua y los fenómenos climáticos." },
    { text: "La capa de la atmósfera que contiene la capa de ozono es",
      options: ["la troposfera", "la estratosfera", "la mesosfera", "la termosfera"],
      correct: 1,
      explanation: "El ozono estratosférico (15-35 km de altitud) filtra la radiación UV nociva." },
    { text: "El principal gas de efecto invernadero emitido por actividades humanas es",
      options: ["oxígeno", "nitrógeno", "dióxido de carbono", "argón"],
      correct: 2,
      explanation: "El CO₂ es el GEI antropogénico más abundante, principalmente de combustión de fósiles." },
    { text: "El clima predominante en la mayor parte del norte de México es",
      options: ["tropical lluvioso", "polar", "seco/desértico", "templado húmedo"],
      correct: 2,
      explanation: "Norte de México: climas BS (semiárido) y BW (árido/desértico) según Köppen." },
    { text: "La densidad de población se mide en",
      options: ["habitantes por km²", "km² por persona", "habitantes por familia", "personas por edad"],
      correct: 0,
      explanation: "Densidad poblacional = habitantes / superficie (hab/km²)." },
    { text: "El país más poblado del mundo en 2023 es",
      options: ["China", "Estados Unidos", "India", "Indonesia"],
      correct: 2,
      explanation: "Desde 2023 la India superó a China como país más poblado (~1.43 mil millones)." },
    { text: "El bloque económico al que pertenece México junto con EE.UU. y Canadá es",
      options: ["MERCOSUR", "Unión Europea", "T-MEC (antes TLCAN)", "ASEAN"],
      correct: 2,
      explanation: "T-MEC (Tratado entre México, EE.UU. y Canadá) entró en vigor en 2020, sucediendo al TLCAN." },
    { text: "El sector económico que se dedica a la extracción de materias primas se llama",
      options: ["primario", "secundario", "terciario", "cuaternario"],
      correct: 0,
      explanation: "Sector primario: agricultura, ganadería, pesca, minería. Secundario: industria. Terciario: servicios." },
    { text: "La principal lengua de origen amerindio hablada en México es",
      options: ["maya", "quechua", "náhuatl", "guaraní"],
      correct: 2,
      explanation: "El náhuatl tiene cerca de 1.7 millones de hablantes en México, la lengua originaria más hablada." },
    { text: "El proceso de concentración de la población en las ciudades se llama",
      options: ["migración pendular", "urbanización", "globalización", "industrialización"],
      correct: 1,
      explanation: "Urbanización: aumento proporcional de la población en zonas urbanas respecto a las rurales." },
    { text: "El golfo de México limita al sur con",
      options: ["Estados Unidos", "Cuba", "México", "Belice"],
      correct: 2,
      explanation: "El Golfo está rodeado por EE.UU. al norte, México al oeste/sur y Cuba al sureste." },
  ],

  espanol: [
    { text: "La función del lenguaje que predomina cuando el emisor expresa sus emociones es",
      options: ["referencial", "emotiva o expresiva", "apelativa", "metalingüística"],
      correct: 1,
      explanation: "Función emotiva: foco en el emisor y sus sentimientos (interjecciones, primera persona)." },
    { text: "Identifica la función del lenguaje en el enunciado: \"¡Cierra la puerta, por favor!\"",
      options: ["referencial", "emotiva", "apelativa", "poética"],
      correct: 2,
      explanation: "Apelativa o conativa: busca influir en el receptor (imperativos, vocativos, preguntas directas)." },
    { text: "La función poética del lenguaje pone el foco en",
      options: ["el referente", "el emisor", "el receptor", "el mensaje en sí mismo"],
      correct: 3,
      explanation: "Función poética: la forma del mensaje cobra protagonismo (literatura, publicidad, refranes)." },
    { text: "La forma del discurso que presenta sucesos en orden cronológico es",
      options: ["descriptiva", "narrativa", "expositiva", "argumentativa"],
      correct: 1,
      explanation: "Narrativa: relata acciones que se desarrollan en el tiempo (cuento, crónica, noticia)." },
    { text: "El discurso argumentativo se caracteriza por",
      options: ["pintar con palabras un lugar.", "exponer información objetiva.", "defender una tesis con razones.", "contar hechos en orden temporal."],
      correct: 2,
      explanation: "Argumentativo: tesis + argumentos + conclusión. Busca convencer." },
    { text: "Identifica al sustantivo abstracto:",
      options: ["mesa", "perro", "amor", "ventana"],
      correct: 2,
      explanation: "Abstracto: designa lo que no se percibe por los sentidos (amor, libertad, justicia)." },
    { text: "La palabra \"rápido\" funciona como adverbio cuando modifica a",
      options: ["un sustantivo.", "un verbo, adjetivo u otro adverbio.", "una preposición.", "una conjunción."],
      correct: 1,
      explanation: "El adverbio modifica al verbo (\"corre rápido\"), al adjetivo (\"muy rápido\") o a otro adverbio (\"bastante rápido\")." },
    { text: "El pronombre personal de tercera persona del singular masculino es",
      options: ["tú", "yo", "él", "nosotros"],
      correct: 2,
      explanation: "Tercera persona singular masculino: él. (Femenino: ella; neutro: ello.)" },
    { text: "El sujeto de la oración \"Los estudiantes leen el libro\" es",
      options: ["el libro", "leen", "los estudiantes", "los"],
      correct: 2,
      explanation: "El sujeto realiza la acción del verbo. ¿Quién lee? Los estudiantes." },
    { text: "Identifica el complemento directo en: \"Compré un libro nuevo\".",
      options: ["compré", "un libro nuevo", "nuevo", "yo (tácito)"],
      correct: 1,
      explanation: "CD responde \"¿qué?\" tras el verbo. ¿Qué compré? Un libro nuevo." },
    { text: "El complemento circunstancial de lugar en \"Estudio en la biblioteca\" es",
      options: ["estudio", "en", "en la biblioteca", "la biblioteca"],
      correct: 2,
      explanation: "CC de lugar: indica dónde ocurre la acción. La frase preposicional completa \"en la biblioteca\"." },
    { text: "La oración \"Cuando llegues, avísame\" contiene una proposición subordinada",
      options: ["sustantiva", "adjetiva", "adverbial temporal", "adverbial causal"],
      correct: 2,
      explanation: "\"Cuando llegues\" expresa una circunstancia de tiempo → subordinada adverbial temporal." },
    { text: "El plural de la palabra \"crisis\" es",
      options: ["crisises", "crísises", "crisis", "crisi"],
      correct: 2,
      explanation: "Sustantivos agudos terminados en -s que no llevan acento en la última: forma invariable (la crisis / las crisis)." },
    { text: "Identifica la palabra correctamente escrita:",
      options: ["habrir", "abrir", "havrir", "ahbrir"],
      correct: 1,
      explanation: "El verbo \"abrir\" se escribe sin h." },
    { text: "Selecciona la palabra que lleva acento ortográfico (tilde):",
      options: ["examen", "examenes (en plural)", "exámenes", "examén"],
      correct: 2,
      explanation: "\"Exámenes\" es esdrújula (acento en la antepenúltima): siempre lleva tilde." },
    { text: "La palabra \"corazón\" es",
      options: ["aguda con tilde", "grave con tilde", "esdrújula", "sobreesdrújula"],
      correct: 0,
      explanation: "Aguda (acento en última sílaba) terminada en -n → lleva tilde." },
    { text: "Identifica el uso correcto de los signos de puntuación:",
      options: ["¿Vienes con nosotros.", "vienes con nosotros?", "¿Vienes con nosotros?", "Vienes con nosotros¿?"],
      correct: 2,
      explanation: "En español los signos de interrogación se abren y cierran: ¿...?" },
    { text: "El significado correcto de \"efímero\" es",
      options: ["eterno", "breve, de corta duración", "permanente", "intenso"],
      correct: 1,
      explanation: "Efímero: que dura poco tiempo (del griego \"de un día\")." },
    { text: "Sinónimo de \"perspicaz\":",
      options: ["distraído", "agudo, sagaz", "torpe", "honesto"],
      correct: 1,
      explanation: "Perspicaz: que observa y comprende rápido; agudo, sagaz." },
    { text: "Antónimo de \"prolijo\":",
      options: ["extenso", "minucioso", "breve, conciso", "esmerado"],
      correct: 2,
      explanation: "Prolijo: largo y detallado en exceso. Antónimo: breve, conciso." },
    { text: "Las palabras \"haber\" y \"a ver\"",
      options: ["significan lo mismo y se usan indistintamente.", "son homófonas pero significan cosas distintas.", "se escriben igual.", "tienen significados sinónimos."],
      correct: 1,
      explanation: "Homófonas: suenan igual, se escriben distinto. \"Haber\" es verbo; \"a ver\" = preposición + verbo (\"voy a ver\")." },
    { text: "Identifica el uso correcto de \"haya\", \"halla\" y \"allá\":",
      options: ["Espero que halla terminado.", "Espero que haya terminado.", "Espero que allá terminado.", "Espero qué haya terminado."],
      correct: 1,
      explanation: "\"Haya\" = subjuntivo de haber. \"Halla\" = encuentra. \"Allá\" = adverbio de lugar." },
    { text: "La conjunción \"sino\" se usa correctamente en:",
      options: ["No vino el lunes sino el martes.", "Si no estudias, reprobarás.", "No sé sino vendrá.", "Lo hizo sino quiso."],
      correct: 0,
      explanation: "\"Sino\" (junto): conjunción adversativa. \"Si no\" (separado): condicional negativa." },
    { text: "Identifica la oración con redacción correcta:",
      options: ["Habían muchas personas en la fiesta.", "Había muchas personas en la fiesta.", "Habían muchísimas personas en la fiesta.", "Habrán muchos invitados."],
      correct: 1,
      explanation: "\"Haber\" impersonal (existir) es invariable en tercera del singular: había, hubo, habrá (NO habían, hubieron)." },
    { text: "El significado de \"vislumbrar\" es",
      options: ["ver con claridad total.", "ver de forma confusa, intuir.", "cerrar los ojos.", "iluminar con fuerza."],
      correct: 1,
      explanation: "Vislumbrar: ver imperfectamente o tener intuición de algo." },
  ],

};
