// Banco de preguntas del Examen Muestra UNAM 2025 — Área 2 Ciencias Biológicas, Químicas y de la Salud
// Sin las 24 preguntas de Matemáticas (Lety da clases de mate).
// Notación: $...$ para fórmulas KaTeX. Las imágenes están en img/

const QUESTIONS = {

  fisica: [
    { n: 1, text: "El desplazamiento de un ferrocarril se describe en la siguiente gráfica (posición x – tiempo t). A partir de los datos mostrados se puede deducir que el movimiento es rectilíneo con",
      image: "img/q1_grafica.png",
      options: ["aceleración constante.", "aceleración variable.", "velocidad constante.", "velocidad variable."],
      correct: 2 },
    { n: 2, text: "Con base en el siguiente sistema de vectores, indica la magnitud del vector resultante en N.",
      image: "img/q2_vectores.png",
      options: ["$\\sqrt{75.8}$", "$\\sqrt{23.8}$", "$\\sqrt{650}$", "$\\sqrt{101.1}$"],
      correct: 3 },
    { n: 3, text: "Sobre un objeto de 100 kg se aplican dos fuerzas (una de 20 N y otra de 30 N) con la misma dirección pero de sentido contrario, ¿cuál es la magnitud de la aceleración del objeto?",
      options: ["$0.1\\ \\mathrm{m/s^2}$", "$0.2\\ \\mathrm{m/s^2}$", "$0.3\\ \\mathrm{m/s^2}$", "$0.5\\ \\mathrm{m/s^2}$"],
      correct: 0 },
    { n: 4, text: "Un objeto se suelta desde el reposo a una altura $H$ sobre el suelo. Determina la relación matemática que permita obtener la rapidez que tendrá el objeto al momento que ha caído una cierta distancia $h$.",
      options: ["$v = (2gh)^{1/2}$", "$v = [2g(H-h)]^{1/2}$", "$v = (2gH)^{1/2}$", "$v = [2g(h-H)]^{1/2}$"],
      correct: 0 },
    { n: 5, text: "La bola A impacta con una rapidez de $6\\ \\mathrm{m/s}$ a una bola B que está en reposo, como se muestra en la figura. Si la bola B tiene el doble de masa que la bola A, ¿cuál es la rapidez con la que sale cada bola después del impacto? Considera que el choque es totalmente elástico.",
      image: "img/q5_bolas.png",
      options: ["$U_A = -2\\ \\mathrm{m/s};\\ U_B = 4\\ \\mathrm{m/s}$", "$U_A = 4\\ \\mathrm{m/s};\\ U_B = 2\\ \\mathrm{m/s}$", "$U_A = 4\\ \\mathrm{m/s};\\ U_B = -2\\ \\mathrm{m/s}$", "$U_A = 2\\ \\mathrm{m/s};\\ U_B = 4\\ \\mathrm{m/s}$"],
      correct: 0 },
    { n: 6, text: "Un sistema está en equilibrio térmico cuando",
      options: ["en un proceso su temperatura no varía.", "su temperatura es igual a la de otro sistema con el que está en contacto térmico.", "se calienta por medio de trabajo.", "su presión y su masa permanecen constantes."],
      correct: 1 },
    { n: 7, text: "Una de las suposiciones de la teoría cinética de los gases es que las moléculas de un gas",
      options: ["carecen de movimiento.", "se mueven lentamente.", "son rígidas.", "son deformables."],
      correct: 2 },
    { n: 8, text: "Una cuerda está atada en un extremo a un punto fijo y en el otro a un vibrador, de manera que se produce un tren de ondas, como el que se muestra en la figura. ¿Cuál es la longitud de onda de la onda estacionaria?",
      image: "img/q8_onda.png",
      options: ["$4.5\\ \\mathrm{cm/ciclo}$", "$90\\ \\mathrm{cm/ciclo}$", "$9\\ \\mathrm{cm/ciclo}$", "$18\\ \\mathrm{cm/ciclo}$"],
      correct: 3 },
    { n: 9, text: "Un aislante eléctrico es un material que",
      options: ["no contiene ninguna corriente eléctrica.", "hace difícil el flujo de corriente eléctrica.", "no puede ser un elemento químicamente puro.", "tiene más electrones que protones en su superficie."],
      correct: 1 },
    { n: 10, text: "Cierto alambre tiene una resistencia $R_1$. ¿Cuál es la resistencia de otro alambre del mismo material pero con la mitad de la longitud y la mitad del diámetro del primero?",
      options: ["$\\dfrac{R_1}{4}$", "$\\dfrac{R_1}{2}$", "$R_1$", "$2R_1$"],
      correct: 3 },
    { n: 11, text: "Isaac Newton consideró a la luz como una",
      options: ["corriente de partículas materiales emitidas por una fuente luminosa.", "onda transversal que al pasar por una rejilla se deforma explicando la refracción.", "marea de rayos que al rodear un obstáculo explican la difracción.", "superposición de ondas que explican la interferencia."],
      correct: 0 },
    { n: 12, text: "¿En qué áreas recibió Madame Curie el premio Nobel?",
      options: ["Física y Biología.", "Medicina y Química.", "Química y Biología.", "Física y Química."],
      correct: 3 },
  ],

  quimica: [
    { n: 23, text: "El elemento con un número atómico 17 y configuración electrónica $1s^2\\,2s^2\\,2p^6\\,3s^2\\,3p^5$ se ubica en la familia",
      options: ["III A", "III B", "II A", "VII A"],
      correct: 3 },
    { n: 24, text: "Una botella contiene X átomos de carbono que pesan 6.0 g. Si se desea que otra botella contenga un número igual de átomos de níquel, ¿qué masa de níquel se debe tomar?",
      options: ["52.7 g", "1.23 g", "12.3 g", "29.4 g"],
      correct: 3 },
    { n: 25, text: "De las siguientes representaciones, identifica en dónde la molécula de agua forma un puente de hidrógeno.",
      image: "img/q25_moleculas.png",
      options: ["Opción A", "Opción B", "Opción C", "Opción D"],
      correct: 1 },
    { n: 26, text: "En la reacción entre el amoniaco ($NH_3$) y el trifluoruro de boro ($BF_3$) el nitrógeno dona un par de electrones al boro por lo que de acuerdo a la teoría ácido–base de Lewis el $NH_3$ es ________ y $BF_3$ es ________.",
      options: ["anfótero — un ácido", "una base — anfótero", "una base — un ácido", "un ácido — una base"],
      correct: 2 },
    { n: 27, text: "¿Cuál es la concentración mol/L de una disolución que contiene 20 g de NaOH en 2 L de disolución?",
      options: ["0.25", "0.50", "0.75", "1.00"],
      correct: 0 },
    { n: 28, text: "¿Qué tipo de compuesto se forma al reaccionar el calcio y el oxígeno?",
      options: ["Un ácido.", "Un carbonato.", "Un óxido ácido.", "Un óxido básico."],
      correct: 3 },
    { n: 29, text: "El efecto invernadero se produce por",
      options: ["disminución de clorofluorocarbonos en la atmósfera.", "disminución de la temperatura del suelo.", "aumento de partículas suspendidas totales.", "aumento en la cantidad de $CO_2$ atmosférico."],
      correct: 3 },
    { n: 30, text: "El siguiente carbohidrato se clasifica como",
      image: "img/q30_carbohidrato.png",
      options: ["aldotriosa.", "cetotriosa.", "aldotetrosa.", "cetotetrosa."],
      correct: 2 },
    { n: 31, text: "Son los dos grupos funcionales presentes en todos los aminoácidos.",
      options: ["$-COO^-$ y $-CONH_2$", "$-CHO$ y $-CONH_2$", "$-CO-$ y $-NH_2$", "$-COOH$ y $-NH_2$"],
      correct: 3 },
    { n: 32, text: "Calcula el valor de entalpía de la reacción química que se representa a continuación. $$H_2O + C \\rightarrow CO + H_2$$ Considera: $$2C + O_2 \\rightarrow 2CO \\quad \\Delta H° = -221\\ \\mathrm{kJ}$$ $$2H_2 + O_2 \\rightarrow 2H_2O \\quad \\Delta H° = -483.6\\ \\mathrm{kJ}$$",
      options: ["$-131.3\\ \\mathrm{kJ}$", "$+131.3\\ \\mathrm{kJ}$", "$-352.3\\ \\mathrm{kJ}$", "$+352.3\\ \\mathrm{kJ}$"],
      correct: 1 },
    { n: 33, text: "En una reacción espontánea a cualquier temperatura, el valor $\\Delta H\\,(-)$, por lo que",
      options: ["$\\Delta S\\,(-)$ y $\\Delta G\\,(+)$.", "$\\Delta S\\,(+)$ y $\\Delta G\\,(+)$.", "$\\Delta S\\,(+)$ y $\\Delta G\\,(-)$.", "$\\Delta S\\,(-)$ y $\\Delta G\\,(-)$."],
      correct: 2 },
    { n: 34, text: "Son compuestos orgánicos en donde todos sus carbonos presentan estructura tetraédrica.",
      options: ["Etino y butino.", "Etileno y benceno.", "Metano y propano.", "Metanal y propanal."],
      correct: 2 },
    { n: 35, text: "¿Qué tipo de reacción representa la polimerización del etileno? $$CH_2=CH_2 \\rightarrow [CH_2-CH_2]_n$$",
      options: ["Adición.", "Condensación.", "Descomposición.", "Sustitución."],
      correct: 0 },
  ],

  biologia: [
    { n: 88, text: "Las células son unidades",
      options: ["centrales y anatómicas.", "originales y microscópicas.", "funcionales y lógicas.", "estructurales y fisiológicas."],
      correct: 3 },
    { n: 89, text: "Se denomina reacción ________ a aquella que libera energía.",
      options: ["endergónica", "exergónica", "reductora", "oxidativa"],
      correct: 1 },
    { n: 90, text: "Las dos moléculas de ácido pirúvico que se producen a partir de la glucólisis, deben ser transformadas químicamente a ________ para ingresar al ciclo de Krebs.",
      options: ["NADH", "$FADH_2$", "ácido oxalacético", "acetil CoA"],
      correct: 3 },
    { n: 91, text: "Los citocromos de la cadena respiratoria se caracterizan por la capacidad de",
      options: ["sintetizar ATP.", "catalizar reacciones REDOX.", "producir moléculas de $O_2$.", "reducir el oxígeno."],
      correct: 1 },
    { n: 92, text: "Una célula presenta un número cromosómico 46 XX. Al dividirse durante la mitosis, formará células con",
      options: ["23 X.", "23 XX.", "46 XX.", "46 X."],
      correct: 2 },
    { n: 93, text: "<em>Saccharomyces cerevisiae</em> es una levadura cuya reproducción asexual se efectúa por medio de",
      options: ["gemación.", "conjugación.", "bipartición.", "esporulación."],
      correct: 0 },
    { n: 94, text: "Resultado de la cruza de una planta heterocigota de flores púrpura y una homocigota de flores blancas, siendo púrpura el carácter dominante.",
      options: ["50 % púrpuras y 50 % blancas.", "100 % blancas.", "100 % púrpuras.", "75 % púrpuras y 25 % blancas."],
      correct: 0 },
    { n: 95, text: "A cualquier cambio que ocurre en la secuencia del DNA de un organismo se le denomina",
      options: ["variación.", "mutación.", "recombinación.", "adaptación."],
      correct: 1 },
    { n: 96, text: "La insulina sintética obtenida mediante la inserción de un plásmido en <em>E. coli</em> es un caso exitoso de la aplicación de la",
      options: ["Biorremediación.", "Ingeniería genética.", "Bioinformática.", "Bioquímica celular."],
      correct: 1 },
    { n: 97, text: "Los organismos pertenecientes a los reinos fungi, vegetal y animal presentan células de tipo",
      options: ["procarióticas.", "heterótrofas.", "eucarióticas.", "autótrofas."],
      correct: 2 },
    { n: 98, text: "Se conoce como ________ a los organismos de una misma área geográfica y a los factores abióticos con los que actúan.",
      options: ["biosfera", "bioma", "población", "ecosistema"],
      correct: 3 },
    { n: 99, text: "Conjunto de organismos de la misma especie que comparten una misma área geográfica y se reproducen entre sí.",
      options: ["Población.", "Ecosistema.", "Bioma.", "Comunidad."],
      correct: 0 },
    { n: 100, text: "Organismos que se alimentan únicamente de plantas.",
      options: ["Productores.", "Consumidores primarios.", "Consumidores secundarios.", "Desintegradores."],
      correct: 1 },
  ],

  historiaUniversal: [
    { n: 101, text: "Recurso que utiliza el historiador para ordenar cronológicamente el estudio del pasado.",
      options: ["Investigación.", "Periodización.", "Selección.", "Observación."],
      correct: 1 },
    { n: 102, text: "El Enciclopedismo del siglo XVIII tuvo como finalidad",
      options: ["concentrar el pensamiento religioso.", "incluir el pensamiento filosófico.", "concentrar todo el conocimiento de su tiempo.", "referirse a los dogmas de la Iglesia."],
      correct: 2 },
    { n: 103, text: "Países que durante la segunda mitad del siglo XIX surgieron como estados independientes a partir del nacionalismo y de la unión comercial.",
      options: ["Inglaterra e Italia.", "Rusia y Turquía.", "Alemania e Italia.", "Alemania y Rusia."],
      correct: 2 },
    { n: 104, text: "Circunstancias económicas y políticas que impulsaron a Alemania, Japón y Estados Unidos de América como potencias internacionales al finalizar el siglo XIX.",
      options: ["Surgir de imperios y colonias de Inglaterra, Francia y Rusia; tener un gobierno y una economía dependientes.", "Contar con un gobierno independiente, economía sólida y conservar su expansionismo militar.", "Ser países independientes con un gobierno autónomo con una economía basada en sus colonias.", "Ser colonias de potencias y haber obtenido su independencia, herederas de los países neocolonialistas."],
      correct: 1 },
    { n: 105, text: "Los Catorce Puntos de Wilson, la creación de la Sociedad de Naciones, la búsqueda de la autodeterminación de los pueblos para la paz, así como el apoyo total a la diplomacia fueron acuerdos de paz de la",
      options: ["Guerra Fría.", "Segunda Guerra Mundial.", "Primera Guerra Mundial.", "Guerra de los Balcanes."],
      correct: 2 },
    { n: 106, text: "Partido de un país del centro de Europa que pregonaba ideas anticomunistas y pretendía formar una aparente unidad nacionalista.",
      options: ["Nacional Socialista.", "Bolchevique.", "Fascio italiana.", "Nacional Falangista."],
      correct: 0 },
    { n: 107, text: "Son los representantes de los siguientes regímenes totalitarios: ________ del militarismo, ________ del fascismo y ________ del nazismo.",
      options: ["Mussolini — Hitler — Hiroito", "Mussolini — Hiroito — Hitler", "Hitler — Mussolini — Hiroito", "Hiroito — Mussolini — Hitler"],
      correct: 3 },
    { n: 108, text: "La OTAN, el Plan Marshall y el apoyo a regímenes democrático liberales caracterizan al bloque ________; en tanto que el bloque ________ se distingue por el Pacto de Varsovia, la Kominform y la Comecon.",
      options: ["socialista — occidental", "socialista — capitalista", "capitalista — occidental", "capitalista — socialista"],
      correct: 3 },
    { n: 109, text: "La Guerra de Corea, la Crisis de los Misiles en Cuba y la Primavera de Praga son conflictos que se presentaron durante la",
      options: ["Gran Depresión.", "Guerra Fría.", "expansión totalitarista.", "descolonización mundial."],
      correct: 1 },
    { n: 110, text: "Los enormes presupuestos militares por la Guerra Fría y el predominio de Estados burocráticos con gasto excesivo fueron causas de la",
      options: ["invasión a Medio Oriente.", "caída del Bloque Soviético.", "formación de la OTAN.", "formación del Pacto de Varsovia."],
      correct: 1 },
  ],

  historiaMexico: [
    { n: 111, text: "Las creencias politeístas, la existencia de técnicas agrícolas, de pueblos tributarios así como los rituales de sacrificios fueron características de",
      options: ["Centroamérica.", "Aridoamérica.", "Oasisamérica.", "Mesoamérica."],
      correct: 3 },
    { n: 112, text: "El movimiento independentista de la Nueva España tuvo como causas externas la",
      options: ["Independencia de los Estados Unidos y la Revolución Francesa.", "Unificación italiana y las Reformas Borbónicas.", "Unificación alemana y la venta de la Florida.", "Independencia de Haití y la anexión de Texas."],
      correct: 0 },
    { n: 113, text: "La restricción de participación política, el control del poder a manos del presidente, así como la promoción de fueros religiosos y militares fueron rasgos del grupo político",
      options: ["centralista.", "federalista.", "monopolista.", "libertador."],
      correct: 0 },
    { n: 114, text: "La Constitución de 1857 consagró los derechos",
      options: ["indígenas.", "eclesiásticos.", "sociales.", "individuales."],
      correct: 3 },
    { n: 115, text: "Movimiento que se opuso al régimen porfirista manifestando su descontento a través del periódico llamado Regeneración.",
      options: ["Magonismo.", "Carrancismo.", "Zapatismo.", "Reyismo."],
      correct: 0 },
    { n: 116, text: "Plan político con el que se inició la lucha en contra del gobierno de Porfirio Díaz.",
      options: ["San Luis Potosí.", "Agua Prieta.", "Empacadora.", "Ayala."],
      correct: 0 },
    { n: 117, text: "Se conoce como Maximato al periodo en el cual ________ mantuvo el control político del país.",
      options: ["Álvaro Obregón.", "Lázaro Cárdenas.", "Plutarco Elías Calles.", "Pascual Ortiz Rubio."],
      correct: 2 },
    { n: 118, text: "Fundó el Partido de la Revolución Mexicana, el Instituto Politécnico Nacional, y la Confederación de Trabajadores de México.",
      options: ["Lázaro Cárdenas.", "Manuel Ávila Camacho.", "Miguel Alemán Valdés.", "Plutarco Elías Calles."],
      correct: 0 },
    { n: 119, text: "La creación de instituciones como el INFONAVIT, la Universidad Autónoma Metropolitana, el Colegio de Bachilleres y el Colegio de Ciencias y Humanidades se llevó a cabo durante el sexenio de",
      options: ["Luis Echeverría Álvarez.", "José López Portillo.", "Miguel de la Madrid.", "Gustavo Díaz Ordaz."],
      correct: 0 },
    { n: 120, text: "La economía de mercado y las privatizaciones entre 1982 y 2000 son parte del",
      options: ["Plan de Once Años.", "Neoliberalismo.", "Estado Benefactor.", "Desarrollo Estabilizador."],
      correct: 1 },
  ],

  literatura: [
    { n: 13, text: "La cabalidad es una propiedad del texto, consiste en que este sea completo y tenga",
      options: ["unidad de sentido.", "datos comprobables.", "elementos de análisis.", "opinión del autor."],
      correct: 0 },
    { n: 14, text: "Dar información, emitir opinión y persuadir al lector son características del texto",
      options: ["periodístico.", "científico.", "poético.", "literario."],
      correct: 0 },
    { n: 15, text: "El autor del texto ________ lo escribe con intención de ser representado.",
      options: ["periodístico", "poético", "dramático", "narrativo"],
      correct: 2 },
    { n: 16, text: "¿A qué género corresponde el siguiente fragmento? <br><br><em>Arturo, el noble rey de Bretaña, cuyas proezas son para nosotros ejemplo de valor y cortesía, al llegar la fiesta que llamamos Pentecostés, la celebró con todo el fasto propio de la realeza, reuniendo a su corte en Caraduel, en el país de Gales.</em>",
      options: ["Épico.", "Lírico.", "Tragedia.", "Dramático."],
      correct: 0 },
    { n: 17, text: "Los autores que conforman una corriente literaria",
      options: ["comparten características en cuanto a su forma de escribir y el interés por desarrollar temas similares; además, viven en una misma época.", "heredan el estilo de quienes los precedieron, comparten una forma de escribir y abordan un género determinado, como la dramaturgia o la novela.", "heredan el estilo de quienes los precedieron, comparten una forma de escribir y muestran interés por desarrollar temas similares.", "abordan un género determinado, como la dramaturgia o la novela, comparten el interés por desarrollar temas similares y viven en una misma época."],
      correct: 0 },
    { n: 18, text: "Corriente literaria que surge en la segunda mitad del siglo XIX, en la cual predomina la objetividad del narrador y la descripción.",
      options: ["Romanticismo.", "Clasicismo.", "Realismo.", "Expresionismo."],
      correct: 2 },
    { n: 19, text: "Son representantes de la Literatura contemporánea.",
      options: ["Mariana Enriquez y José Saramago.", "Frank Kafka y Charlotte Brontë.", "Nicolás Gógol y Jane Austen.", "Mary Shelley y Luigi Pirandello."],
      correct: 0 },
    { n: 20, text: "Identifica la respuesta que presenta las características esenciales del cuento.",
      options: ["Subgénero con amplio número de personajes, trama simple y de gran extensión.", "Subgénero en prosa que plantea un solo problema y contiene un final sorpresivo.", "Texto literario cuyos personajes poseen hondura psicológica y de trama más o menos compleja.", "Texto de carácter expositivo en el que se narra una breve historia dialogada y de carácter ficticio."],
      correct: 1 },
    { n: 21, text: "Identifica la ficha hemerográfica.",
      options: ["Dosal Gómez, M. R., et al. (2001). <em>Lengua española. Español IV</em>. Patria Cultural.", "García Márquez, G. (2003). \"Cómo eran mis compañeros muertos en el mar\" en <em>Relato de un náufrago</em>. De Bolsillo.", "Peguero, R. (2005, 31 septiembre). \"La filosofía de lucro, el gran mito de la edad contemporánea: Roa Bastos\". <em>El país</em>.", "Ocampo de Gómez, A. M. y Prado Velázquez, E. (1976). <em>Diccionario de escritores mexicanos</em>. UNAM, Centro de Estudios Literarios."],
      correct: 2 },
    { n: 22, text: "¿De qué tipo es la siguiente ficha?<br><br><em>Trejo Rivas, A. y Rosa Pirres, A. (2007). Rimas, rondas y canciones. Editores Mexicanos Unidos. Conformado por apenas 92 páginas este texto de divulgación (sin mayor aparato crítico) tiene, sin embargo, como mérito principal, presentar (en su sección \"Rondas\") versiones tradicionales, extrañas o antiguas de canciones infantiles que hoy se consideran de moda. Ejemplo de ello es una versión de la muy conocida \"Chuchugua\", que se encuentra en las páginas 63 – 64.</em>",
      options: ["Comentario.", "Textual.", "Paráfrasis.", "Resumen."],
      correct: 0 },
  ],

  geografia: [
    { n: 36, text: "Si en el huso horario 0° son las 20:00 horas, ¿qué hora será en la Ciudad de Tijuana, México, cuyo huso horario es de 120° W?",
      options: ["10:00 h.", "11:00 h.", "12:00 h.", "13:00 h."],
      correct: 2 },
    { n: 37, text: "El choque de la Placa de Cocos y la Norteamericana produce sismos que afectan principalmente a los estados de",
      options: ["Puebla, Morelos y Querétaro.", "Michoacán, Guerrero y Oaxaca.", "Sonora, Sinaloa y Chihuahua.", "Veracruz, Tabasco y Campeche."],
      correct: 1 },
    { n: 38, text: "Principal entidad federativa en México productora de cobre.",
      options: ["Coahuila.", "Sonora.", "San Luis Potosí.", "Guanajuato."],
      correct: 1 },
    { n: 39, text: "El río que comunica a Moscú con el mar Caspio es",
      options: ["Ural.", "Volga.", "Lena.", "Duina."],
      correct: 1 },
    { n: 40, text: "El ________ sirve para la industria pesada.",
      options: ["manganeso", "carbón", "zinc", "cobalto"],
      correct: 1 },
    { n: 41, text: "El aumento y la retención de bióxido de carbono en la parte inferior de la atmósfera está generando",
      options: ["el intercambio del agua.", "el cambio climático global.", "la alteración del viento.", "la modificación del relieve."],
      correct: 1 },
    { n: 42, text: "Los países desarrollados reciben un alto número de inmigrantes porque",
      options: ["cuentan con políticas públicas de seguro de desempleo.", "presentan rasgos culturales similares.", "cuentan con mejores ofertas educativas.", "requieren mano de obra no especializada."],
      correct: 3 },
    { n: 43, text: "Conjunto de empresas a nivel mundial que controlan en el mercado la producción y venta de uno o varios productos.",
      options: ["Oligopolio.", "Monopolio.", "Duopolio.", "Tripolio."],
      correct: 0 },
    { n: 44, text: "La región de los Balcanes tuvo grandes cambios territoriales debido a",
      options: ["la separación de Chechenia.", "la unificación alemana.", "el expansionismo de Rumania.", "la desintegración de Yugoslavia."],
      correct: 3 },
    { n: 45, text: "La primera zona pesquera de México se ubica en la península de Baja California y exporta productos como el",
      options: ["camarón y el bacalao.", "huachinango y la jaiba.", "ostión y el robalo.", "atún y la sardina."],
      correct: 3 },
  ],

  espanol: [
    { n: 70, text: "Selecciona el párrafo en el que predomina la función referencial de la lengua.",
      options: [
        "Si las aves desaparecieran, nuestro planeta se vería privado del espectáculo de su vuelo. Sin embargo, ése sería un mal menor, ya que de ellas depende la polinización de las plantas, la dispersión de las semillas, el control de los insectos y la eliminación de cadáveres en descomposición.",
        "Si las prodigiosas aves lamentablemente desaparecieran, nos veríamos privados del maravilloso espectáculo de su armónico y encantador vuelo. Más considero que ello sería sólo el mal menor, ya que nadie podría fecundar las muy valiosas plantas o dispersar las tiernas semillas.",
        "Es claro que si las aves desaparecieran, nuestro planeta se vería privado del espectáculo de su vuelo. Pero además debemos salvarlas, urgentemente, ya que de ellas depende tanto la polinización de las plantas como la dispersión de las semillas, el control de los insectos o la eliminación de cadáveres de animales.",
        "Si las aves desaparecieran ello implicaría que estuviéramos destinados a perecer y perdernos del espectáculo de la naturaleza. ¡Ay de nosotros!, perdidos en nuestro egoísmo y en la desesperanza, se diluye el olor de la flor, las semillas y los frutos. El alimento de la tierra que nos hace sentir vivos."
      ],
      correct: 0 },
    { n: 71, text: "¿En cuál de los siguientes textos predomina la función apelativa de la lengua?",
      options: [
        "Regularmente eres un buen conversador, pues no agobias a tus amigos con información para demostrar que eres un sabihondo. Me doy cuenta que sabes transmitir con serenidad y emoción tus experiencias, aunque has leído poco.",
        "Resulta una grata experiencia dialogar con personas sencillas que no alardean de sus conocimientos. La gente sencilla, aunque no haya leído mucho, tiene más que decir, pues ha sabido encontrar sentido a sus experiencias.",
        "Los buenos conversadores no agobian al otro con datos para demostrar que dominan muchos conocimientos; al contrario, saben transmitir con serenidad y emoción lo que han visto, escuchado o leído. Toma en cuenta esto siempre que dialogues.",
        "Los clásicos preceptos de la buena educación disponen que durante una conversación se hable poco de uno mismo (salvo que el interlocutor sea un amigo íntimo), y mucho menos ponerse a sí mismo como ejemplo."
      ],
      correct: 2 },
    { n: 72, text: "Señala la forma del discurso que predomina en el siguiente fragmento. <br><br><em>Después de la Conquista de Tenochtitlan, hacia 1529, Hernán Cortés ordenó traer frailes dominicos para que evangelizaran a los indios en las tierras con que el rey Carlos V le recompensaba por los servicios prestados a la Corona, y que incluían áreas de Coyoacán, Tacubaya y Cuajimalpa, entre otras dentro de la cuenca. Estos primeros dominicos fundaron conventos como el de San Juan Bautista (Coyoacán) y compartieron con los franciscanos el trabajo de adoctrinar a los naturales en la fe cristiana.</em>",
      options: ["Narrativa.", "Descriptiva.", "Expositiva.", "Argumentativa."],
      correct: 0 },
    { n: 73, text: "Identifica el texto en el que predomina la forma del discurso argumentativa.",
      options: [
        "Un hombre extraño me grita desde la puerta: \"despiértese, que es tarde\". Le contesto yo: \"despiértese usted, que buena falta le hace\". Pero el muy obstinado me sigue soñando.",
        "En Español, lo contrario de IN (como prefijo privativo, claro) suele ser la misma palabra, pero sin esa sílaba. Sí, ya sé: insensato y sensato, indócil y dócil, ¿no? Parcialmente correcto. No olvide, muchacho, que lo contrario del invierno no es el vierno sino el verano.",
        "Aprende, viaja, estudia, habla, escribe, trabaja, sube y baja, Miguel. Miguel, levántate y anda.",
        "Quien no quiere pensar es un fanático porque deja que otros piensen por él; quien no puede pensar es un idiota porque deja sus decisiones en manos de otros; quien no osa pensar es un cobarde porque deja su vida en manos de alguien más."
      ],
      correct: 3 },
    { n: 74, text: "<strong>Lee el siguiente texto y contesta de la pregunta 74 a la 78.</strong><br><br><em>El ser humano ha generado 8.300 millones de toneladas de plástico</em><br><br>Estamos rodeados de plástico. Éste inunda nuestra vida diaria en todo tipo de objetos —desde bolsas para hacer la compra hasta materiales de construcción e incluso ingredientes cosméticos—, y sus versátiles características y su bajo precio lo han convertido en un imprescindible. Sin embargo, ese \"bajo precio\" se está convirtiendo en un coste muy alto a nivel medioambiental.<br><br>Según un estudio de investigadores de la Universidad de Georgia y otras, los seres humanos hemos generado un total de 8.300 millones de toneladas de plástico. De esas, 6.300 millones son residuos: solo el 9 % se ha reciclado, 12 % se ha incinerado y el 79 % yace en vertederos o en el medio ambiente. La producción pasó de 2 millones de toneladas en 1950 a más de 400 millones en 2015.<br><br>Jenna Jambeck (coautora) explica que \"la mayoría de los plásticos no se biodegradan, por lo que los residuos podrían estar con nosotros durante cientos o miles de años. Nuestras estimaciones subrayan la necesidad de pensar en los materiales que usamos y en nuestras prácticas de gestión de residuos\".<br><br><strong>¿Cuál de las siguientes opciones corresponde a la idea principal del texto?</strong>",
      options: [
        "La vida útil del plástico es muy corta y su mayor mercado está en el sector del empaquetado.",
        "Es alarmante el crecimiento exponencial en la producción de plásticos de corta vida útil, que se ha tenido lugar desde hace más de 13 años.",
        "El plástico producido en las últimas décadas se puede comparar con 80 millones de ballenas azules.",
        "Es urgente implementar medidas para gestionar la creciente cantidad de desechos plásticos, con base en datos generados a través de la investigación."
      ],
      correct: 3 },
    { n: 75, text: "(Texto sobre plásticos, ver pregunta 74) De acuerdo al texto, \"las prácticas de gestión de residuos\", se refieren a la",
      options: [
        "reducción de los costos y el uso variado de materiales producidos por el ser humano.",
        "utilización razonable de los materiales producidos por el ser humano.",
        "utilización desmedida de plásticos de un solo uso en la vida cotidiana.",
        "disposición, manejo y reaprovechamiento sostenible de los residuos plásticos."
      ],
      correct: 3 },
    { n: 76, text: "(Texto sobre plásticos, ver pregunta 74) A partir de la lectura se infiere que",
      options: [
        "las investigaciones sobre los daños que causa el plástico en el medio ambiente están encabezadas por especialistas estadounidenses.",
        "se deben tomar acciones para disminuir la producción mundial del plástico de uso cosmético y comercial, a pesar de su bajo costo.",
        "el plástico ha aumentado considerablemente su producción a partir de los años 50 derivado de una sociedad más consumista.",
        "se debe investigar más sobre los posibles usos del plástico para estabilizar los índices de contaminación ambiental."
      ],
      correct: 2 },
    { n: 77, text: "(Texto sobre plásticos, ver pregunta 74) La investigadora Jenna Jambeck se muestra",
      options: [
        "alarmada por las estadísticas de la acumulación de plásticos que van en aumento, pero se trabaja para disminuir la contaminación.",
        "desconcertada porque hay muchos productos elaborados a base de plástico en los sectores cosmético y del empaquetado.",
        "preocupada por la producción irracional y la mala gestión de plásticos no biodegradables.",
        "interesada en dar a conocer los datos estadísticos globales sobre la acumulación de plásticos en los vertederos."
      ],
      correct: 2 },
    { n: 78, text: "(Texto sobre plásticos, ver pregunta 74) La intención de la autora al escribir este texto es",
      options: [
        "comparar los diferentes tipos de contaminantes ambientales y sus consecuencias en el planeta.",
        "divulgar los datos estadísticos de los residuos plásticos para ver cuánto han crecido en los últimos años.",
        "concientizar sobre el uso excesivo del plástico y la importancia de una gestión adecuada de los residuos.",
        "difundir los orígenes de la contaminación por desechos plásticos no biodegradables."
      ],
      correct: 2 },
    { n: 79, text: "En el siguiente párrafo lo que está en letra mayúscula es una oración<br><br><em>Todas las tardes el arquitecto tomaba el café QUE LE PREPARABAN EN LA HOSTERÍA y luego repasaba el diario de palmo a palmo.</em>",
      options: ["coordinada.", "secundaria.", "principal.", "yuxtapuesta."],
      correct: 1 },
    { n: 80, text: "En el siguiente enunciado las palabras en mayúsculas constituyen el<br><br><em>Chuang Tzu presencia A LAS AFUERAS DEL PALACIO la lucha entre dos serpientes.</em>",
      options: ["complemento indirecto.", "complemento circunstancial.", "complemento directo.", "predicado nominal."],
      correct: 1 },
    { n: 81, text: "Selecciona la oración correctamente redactada.",
      options: [
        "Una mujer ésta sentada sola en una casa; sabe que no hay nadie más en el mundo, todos los otros seres han muerto...Golpean a la puerta.",
        "Una mujer esta sentada sola en una casa. Sabe que no hay nadie mas en el mundo. Todos los otros seres han muerto. Golpean a la puerta...",
        "Una mujer esta sentada sola en una casa: sabe que no hay nadie mas en el mundo; todos los otros seres han muerto; golpean a la puerta.",
        "Una mujer está sentada sola en una casa. Sabe que no hay nadie más en el mundo: todos los otros seres han muerto. Golpean a la puerta."
      ],
      correct: 3 },
    { n: 82, text: "Elige la opción con la redacción apropiada.",
      options: [
        "Los checoslovacos combatían en las calles y se oponían a la dictadura.",
        "Un sinnúmero de feligreses acudieron a la Villa.",
        "La creación de muchas cosas no se tenían contempladas.",
        "Los constantes flujo y reflujo de divisas provocó alarma."
      ],
      correct: 0 },
    { n: 83, text: "Identifica el párrafo que está redactado correctamente.",
      options: [
        "Durante décadas se ha repetido, casi como un mantra \"las mujeres viven más que los hombres\". Pero a simple vista podría parecer una cuestión de estilo de vida o de decisiones personales. Lo cierto es que esta diferencia de esperanza de vida, está profundamente enraizada en nuestra historia evolutiva.",
        "Durante décadas, se ha repetido casi como un mantra: las mujeres viven más que los hombres. Aunque a simple vista podría parecer una cuestión de estilo de vida o de decisiones personales, lo cierto es que esta diferencia de esperanza de vida está profundamente enraizada en nuestra historia evolutiva.",
        "Durante décadas se ha repetido, casi como un mantra, las mujeres viven más que los hombres. Ya que a simple vista, podría parecer una cuestión de estilo de vida o de decisiones personales, lo cierto es que esta diferencia de esperanza de vida está profundamente enraizada en nuestra historia evolutiva.",
        "Durante décadas se ha repetido casi como \"un mantra\" las mujeres viven más que los hombres; aunque a simple vista podría parecer una cuestión de estilo de vida o de decisiones personales: lo cierto es que esta diferencia de esperanza de vida está profundamente enraizada en nuestra historia evolutiva."
      ],
      correct: 1 },
    { n: 84, text: "¿Cuál es el sinónimo para la palabra \"remembranzas\" como está en el texto?<br><br><em>El viejo Manuel pide al ángel que lo haga niño. \"¡Son tan dulces sus remembranzas de la niñez!\" El ángel lo aniña. Ahora Manuelito no tiene remembranzas.</em>",
      options: ["Conmemoraciones.", "Recuerdos.", "Rememoraciones.", "Añoranzas."],
      correct: 1 },
    { n: 85, text: "Selecciona la opción que contenga las palabras correctas para cada caso.<br><br><em>Un técnico unió el ________ a la pieza principal; otro soldó los cables ________ que quedaron firmemente unidos. Aproximadamente se produce un ________ de piezas al día en esta fábrica de ________.</em>",
      options: ["tuvo — hasta — ciento — vienes", "tubo — asta — siento — vienes", "tubo — hasta — ciento — bienes", "tuvo — asta — siento — bienes"],
      correct: 2 },
    { n: 86, text: "Selecciona la opción con las grafías que complementan correctamente el enunciado.<br><br><em>Los niños que no ha___an hecho la tarea a___er porque no o___eron la indicación, tendrán que ha___ar el significado de las palabras en un diccionario de términos Caste___anos.</em>",
      options: ["y — y — y — ll — ll", "ll — y — ll — ll — ll", "y — y — y — y — ll", "y — ll — y — y — ll"],
      correct: 0 },
    { n: 87, text: "¿En cuál de los siguientes enunciados se aplican correctamente las mayúsculas?",
      options: [
        "Si vas al puesto de periódicos, compra <em>México desconocido</em>; luego, acude a la librería y adquiere <em>Antes del Fin</em>, un libro maravilloso de Ernesto Sábato, donde el autor afirma: \"Los excluidos no tienen justicia que los defienda\".",
        "Si vas al puesto de periódicos, compra <em>México Desconocido</em>; luego, acude a la librería y adquiere <em>Antes del fin</em>, un libro maravilloso de Ernesto Sábato, donde el autor afirma: \"Los excluidos no tienen justicia que los defienda\".",
        "Si vas al puesto de periódicos, compra <em>México desconocido</em>; luego, acude a la librería y adquiere <em>Antes del Fin</em>, un libro maravilloso de Ernesto Sábato, donde el autor afirma: \"los excluidos no tienen justicia que los defienda\".",
        "Si vas al puesto de periódicos, compra <em>México Desconocido</em>; luego, acude a la librería y adquiere <em>Antes del fin</em>, un libro maravilloso de Ernesto Sábato, donde el autor afirma: \"los excluidos no tienen justicia que los defienda\"."
      ],
      correct: 1 },
  ],

};

// Configuración de bloques
const BLOCKS = {
  naturales: {
    title: "Bloque 1 · Naturales",
    subtitle: "Física · Química · Biología",
    accent: "#00DEC8",
    composition: [
      { subject: "fisica", count: 8, label: "Física" },
      { subject: "quimica", count: 8, label: "Química" },
      { subject: "biologia", count: 8, label: "Biología" },
    ],
  },
  historia: {
    title: "Bloque 2 · Historia",
    subtitle: "Universal · México",
    accent: "#FF00AA",
    composition: [
      { subject: "historiaMexico", count: 10, label: "H. de México" },
      { subject: "historiaUniversal", count: 10, label: "H. Universal" },
    ],
  },
  sociales: {
    title: "Bloque 3 · Sociales y Lenguaje",
    subtitle: "Literatura · Geografía · Español",
    accent: "#4A0080",
    composition: [
      { subject: "literatura", count: 8, label: "Literatura" },
      { subject: "geografia", count: 8, label: "Geografía" },
      { subject: "espanol", count: 8, label: "Español" },
    ],
  },
};

const SUBJECT_LABELS = {
  fisica: "Física",
  quimica: "Química",
  biologia: "Biología",
  historiaUniversal: "Historia Universal",
  historiaMexico: "Historia de México",
  literatura: "Literatura",
  geografia: "Geografía",
  espanol: "Español",
};
